//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT_TYPE_LOOKUP
    {
        public int ACC_TYPE_ID { get; set; }
        public string ACC_TYPE_DESC { get; set; }
        public string TYPE { get; set; }
        public Nullable<bool> STATUS { get; set; }
    }
}
