//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIGURATION
    {
        public string KEY_REMAP { get; set; }
        public string LONG_TEMP_NAMES { get; set; }
        public string TRACE { get; set; }
        public string PDF_LICENCE_LEVEL { get; set; }
        public int CONFIGURATION_ID { get; set; }
    }
}
