//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_DEFAULT
    {
        public string DEFAULT_NOMINAL_CODE { get; set; }
        public Nullable<bool> IS_NOMINALCODE_SALES { get; set; }
        public string DEFAULT_TAX_CODE { get; set; }
        public Nullable<bool> IS_TAXCODE_SALE { get; set; }
        public string CURRENCY_CODE { get; set; }
        public string DEPARTMENT { get; set; }
        public string REPORTING_PASSWORD { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public int DEFAULT_ID { get; set; }
    }
}
