//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_DOCUMENT
    {
        public string FILE_NAME { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string TYPE_ID_DOC { get; set; }
        public string SIZE { get; set; }
        public string TAG { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public int DOCUMENT_ID { get; set; }
    }
}
