//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_CREDIT_CONTROL
    {
        public int CREDIT_ID { get; set; }
        public Nullable<decimal> CREDIT_LIMIT { get; set; }
        public Nullable<int> SETTLEMENT_DUE_DAYS { get; set; }
        public Nullable<decimal> SETTLEMENT_DISCOUNT { get; set; }
        public Nullable<int> PAYMENT_DUE_DAYS { get; set; }
        public Nullable<int> AVG_TIME { get; set; }
        public string PAYMENT_DUE_FROM { get; set; }
        public string TRADING_TERMS { get; set; }
        public string CREDIT_REF { get; set; }
        public string BUREAU { get; set; }
        public Nullable<bool> PRIORITY_CUSTOMER { get; set; }
        public string CREDIT_POSITION { get; set; }
        public string ACCOUNT_STATES { get; set; }
        public string DUNS_NUMBER { get; set; }
        public Nullable<System.DateTime> ACCOUNT_OPENED { get; set; }
        public Nullable<System.DateTime> LAST_CREDIT_REVIEW { get; set; }
        public Nullable<System.DateTime> NEXT_CREDIT_REVIEW { get; set; }
        public Nullable<System.DateTime> APPLICATION_DATE { get; set; }
        public Nullable<System.DateTime> DATE_RECEIVED { get; set; }
        public string MEMO { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public Nullable<bool> IS_CHANGE_CREDIT { get; set; }
        public Nullable<bool> IS_TERMS_AGREED { get; set; }
        public Nullable<bool> IS_RESTRICT_MAILING { get; set; }
        public Nullable<bool> IS_ACCOUNT_HOLD { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
    }
}
