//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_DELIVERY_ADDRESS
    {
        public int DELIVERY_ID { get; set; }
        public Nullable<int> COMPANY_ID { get; set; }
        public string DELIVERY_CODE { get; set; }
        public string DELIVERY_COMPANY_NAME { get; set; }
        public string ADDRESS { get; set; }
        public string COUNTRY { get; set; }
        public string CONTACTS { get; set; }
        public string TELEPHONE { get; set; }
        public string FAX { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public string STATUS { get; set; }
        public string POSTCODE { get; set; }
        public string EC_COUNTRY { get; set; }
        public string DELIVERY_MODE { get; set; }
        public string DELIVERY_TIME { get; set; }
        public string SAME_STATEMENT { get; set; }
    }
}
