//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUP_LOOKUP
    {
        public string GROUP_CODE { get; set; }
        public string GROUP_TYPE_CODE { get; set; }
        public string GROUP_DESCRIPTION { get; set; }
        public int GROUP_ID { get; set; }
    }
}
