//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class NATURE_OF_PRODUCT_LOOKUP
    {
        public string NATURE_OF_PRODUCT_NAME { get; set; }
        public string NATURE_OF_PRODUCT_DESC { get; set; }
        public int NATURE_OF_PRODUCT_ID { get; set; }
    }
}
