//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOMINAL_ACCOUNT_DETAILS_LOOKUP
    {
        public int NOMINAL_GROUP_ID { get; set; }
        public string NOMINAL_GROUP_CODE { get; set; }
        public string NOMINAL_GROUP_DESC { get; set; }
    }
}
