//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_TYPE_LOOKUP
    {
        public string PRODUCT_TYPE_NAME { get; set; }
        public string PRODUCT_TYPE_DESCRIPTION { get; set; }
        public int PRODUCT_TYPE_ID { get; set; }
    }
}
