//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_PICTURE
    {
        public string PRODUCT_CODE { get; set; }
        public string PICTURE_NAME { get; set; }
        public int PICTURE_ID { get; set; }
    }
}
