//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public int PRODUCT_ID { get; set; }
        public Nullable<int> COMPANY_ID { get; set; }
        public string PRODUCT_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string BIN { get; set; }
        public string PRODUCT_TYPE1 { get; set; }
        public string PRODUCT_TYPE2 { get; set; }
        public string VAT_RATE { get; set; }
        public string GROUP { get; set; }
        public string DISCONTINUED { get; set; }
        public string COMMISSION { get; set; }
        public string BAR_CODE { get; set; }
        public string UNIT_DESC { get; set; }
        public string ALTERNATIVE { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public Nullable<decimal> COST_PRICE { get; set; }
        public Nullable<decimal> LAST_SALE { get; set; }
        public Nullable<decimal> RETAIL_PRICE { get; set; }
        public Nullable<decimal> RETAIL_STANDARD { get; set; }
        public Nullable<decimal> TRADE { get; set; }
        public Nullable<decimal> WHOLESALE { get; set; }
        public Nullable<decimal> TRADE_DISC { get; set; }
        public Nullable<decimal> WHOLESALE_DISC { get; set; }
        public Nullable<decimal> RETAIL_MARGIN { get; set; }
        public Nullable<decimal> TRADE_MARGIN { get; set; }
        public Nullable<decimal> WHOLESALE_MARGIN { get; set; }
        public Nullable<decimal> SELL_PRICE1 { get; set; }
        public Nullable<decimal> SELL_PRICE2 { get; set; }
        public Nullable<decimal> SELL_PRICE3 { get; set; }
        public Nullable<decimal> SELL_PRICE4 { get; set; }
        public Nullable<decimal> SELL_QTY2 { get; set; }
        public Nullable<decimal> SELL_QTY3 { get; set; }
        public Nullable<decimal> SELL_QTY4 { get; set; }
        public Nullable<decimal> SELL_MARGIN2 { get; set; }
        public Nullable<decimal> SELL_MARGIN3 { get; set; }
        public Nullable<decimal> SELL_MARGIN4 { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public string STATUS { get; set; }
    }
}
