//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_MISCELLANEOUS
    {
        public int PROD_MISC_ID { get; set; }
        public Nullable<int> COMPANY_ID { get; set; }
        public string PRODUCT_CODE { get; set; }
        public Nullable<decimal> SALES_AC1 { get; set; }
        public Nullable<decimal> SALES_AC2 { get; set; }
        public Nullable<decimal> SALES_AC3 { get; set; }
        public Nullable<decimal> SALES_AC4 { get; set; }
        public Nullable<decimal> SALES_AC5 { get; set; }
        public Nullable<decimal> PERCENT1 { get; set; }
        public Nullable<decimal> PERCENT2 { get; set; }
        public Nullable<decimal> PERCENT3 { get; set; }
        public Nullable<decimal> PERCENT4 { get; set; }
        public Nullable<decimal> PERCENT5 { get; set; }
        public Nullable<decimal> PERCENT1_CAL1 { get; set; }
        public Nullable<decimal> PERCENT1_CAL2 { get; set; }
        public Nullable<decimal> PERCENT1_CAL3 { get; set; }
        public string DESCRIPTION1 { get; set; }
        public string DESCRIPTION2 { get; set; }
        public string DESCRIPTION3 { get; set; }
        public string DESCRIPTION4 { get; set; }
        public string DESCRIPTION5 { get; set; }
        public string CODE { get; set; }
        public Nullable<decimal> MIN_ORDER { get; set; }
        public string DESC { get; set; }
        public Nullable<decimal> REORDER { get; set; }
        public Nullable<decimal> MS_QUANTITY { get; set; }
        public string SUPPLIER_CODE1 { get; set; }
        public string SUPPLIER_CODE2 { get; set; }
        public string GROUP1 { get; set; }
        public string GROUP2 { get; set; }
        public string GROUP3 { get; set; }
        public string GROUP4 { get; set; }
        public string GROUP5 { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public string STATUS { get; set; }
    }
}
