//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_ASSEMBLED_ITEMS
    {
        public int PA_ID { get; set; }
        public Nullable<int> PA_ITEM_ID { get; set; }
        public string PRODUCT_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string BIN { get; set; }
        public string PRODUCT_TYPE1 { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public Nullable<decimal> COST_PRICE { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
    }
}
