//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECURRING_SALES_INVOICE
    {
        public string INVOICE_TO { get; set; }
        public string DELIVERY_TO { get; set; }
        public string ORDER_REF { get; set; }
        public string ORDER_DESC { get; set; }
        public string SALES_PERSON { get; set; }
        public string MARKET_CODE { get; set; }
        public string FREQUENCY { get; set; }
        public string CURRENT_STATUS { get; set; }
        public Nullable<System.DateTime> LAST_POSTED { get; set; }
        public Nullable<System.DateTime> PROCESS_NEXT_OCCUR { get; set; }
        public Nullable<int> NUM_OF_TIME_TO_POST { get; set; }
        public Nullable<decimal> ORDER_NET_AMOUNT { get; set; }
        public int RECURR_SALES_INVOICE_ID { get; set; }
    }
}
