//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECURRING_SALES_LINE
    {
        public string PRODUCT_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> ORDER_QTY { get; set; }
        public Nullable<decimal> UNIT_PRICE { get; set; }
        public Nullable<decimal> DISCOUNT_PERCENT { get; set; }
        public Nullable<decimal> LINE_AMOUNT { get; set; }
        public int RECURRING_SALES_LINE_ID { get; set; }
        public int RECURRING_SALES_INVOICE_ID { get; set; }
    }
}
