//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALES_ORDER_LINE_ITEM
    {
        public int LINE_ITEM_ID { get; set; }
        public string ORDER_NO { get; set; }
        public string PRODUCT_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> ORDER_QTY { get; set; }
        public Nullable<decimal> UNIT_PRICE { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public Nullable<int> VAT { get; set; }
        public Nullable<decimal> LINE_AMOUNT { get; set; }
    }
}
