//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALES_JOURNAL_DEBIT
    {
        public int JOURNAL_ID { get; set; }
        public string LEDGER { get; set; }
        public string TRX_TYPE { get; set; }
        public string POSTING_NO { get; set; }
        public Nullable<System.DateTime> POSTING_DATE { get; set; }
        public string POSTING_TYPE { get; set; }
        public string DEF_DIST { get; set; }
        public string GENERAL_CODE { get; set; }
        public string GENERAL_NAME { get; set; }
        public string REF_NO { get; set; }
        public Nullable<System.DateTime> INV_DATE { get; set; }
        public Nullable<System.DateTime> INV_EXP_DATE { get; set; }
        public string DESCRIPTION { get; set; }
        public string PROJECT { get; set; }
        public Nullable<decimal> OS_BAL { get; set; }
        public Nullable<decimal> CREDIT_REMAINING { get; set; }
        public Nullable<decimal> NET_BAL { get; set; }
        public Nullable<decimal> TAX_AMT { get; set; }
        public Nullable<decimal> TOTAL_AMT { get; set; }
        public Nullable<decimal> COST { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public string STATUS { get; set; }
    }
}
