//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALESORDER_CUSTOMER_OTHER_DETAILS
    {
        public int OTHER_DETAILS_ID { get; set; }
        public Nullable<int> NO_OF_COPIES { get; set; }
        public string DEL { get; set; }
        public string MODE { get; set; }
        public Nullable<System.DateTime> EXPECTED_SHIP { get; set; }
        public Nullable<System.DateTime> EXPECTED_PAYMENT { get; set; }
        public string ORDER_NO { get; set; }
        public Nullable<System.DateTime> LAST_CHANGE_SYSTEM_DATE { get; set; }
    }
}
