//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALES_ORDER_DELIVERY
    {
        public int SALESORDER_DELIVERY_ID { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string ORDER_NO { get; set; }
        public int DELIVERY_ID { get; set; }
        public Nullable<System.DateTime> DELIVERY_DATE { get; set; }
        public Nullable<System.DateTime> TRANSACTION_DATE { get; set; }
        public Nullable<bool> DELIVERY_STATUS { get; set; }
    }
}
