//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALESORDER_CUSTOMER_DELIVERY_TO
    {
        public int SALESORDER_CUSTOMER_DELIVERY_TO_ID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string ADDRESS { get; set; }
        public string POSTCODE { get; set; }
        public string COUNTRY { get; set; }
        public string CONTACT { get; set; }
    }
}
