//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALES_QUICK_JOURNAL
    {
        public int QUICKJOURNAL_ID { get; set; }
        public string QUICKJOURNAL_CODE { get; set; }
        public Nullable<System.DateTime> JOURNAL_DATE { get; set; }
        public string CUSTOMER { get; set; }
        public string REFERENCE { get; set; }
        public string JOURNAL_DESC { get; set; }
        public string NL_ACC1 { get; set; }
        public string NL_ACC2 { get; set; }
        public string VAT_PER { get; set; }
        public Nullable<decimal> TOTAL_VAT { get; set; }
        public Nullable<decimal> NET_AMOUNT { get; set; }
        public Nullable<decimal> TOTAL_AMOUNT { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public string STATUS { get; set; }
        public Nullable<int> COMPANY_ID { get; set; }
    }
}
