//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALES_VAT_LINE
    {
        public int VAT_LINE_ID { get; set; }
        public Nullable<int> ORDER_ID { get; set; }
        public Nullable<decimal> VAT_RATE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> NET_AMOUNT { get; set; }
        public Nullable<decimal> VAT_AMOUNT { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
    }
}
