//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALESORDER_CUSTOMER_RECURRING_SALES_LINES
    {
        public int RECURRING_SALES_LINES_ID { get; set; }
        public string PRODUCT { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> ORDER_QTY { get; set; }
        public Nullable<decimal> UNIT_PRICE { get; set; }
        public Nullable<decimal> DISC_PERCENT { get; set; }
        public Nullable<decimal> LINE_AMOUNT { get; set; }
    }
}
