//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALES_ORDER
    {
        public int SALESORDER_ID { get; set; }
        public string INVOICE_TO { get; set; }
        public string DELIVERY_TO { get; set; }
        public string ORDER_NO { get; set; }
        public string ORDER_REF { get; set; }
        public Nullable<System.DateTime> ORDER_DATE { get; set; }
        public string SALES_PERSON { get; set; }
        public string MARKET_CODE { get; set; }
        public Nullable<decimal> OVERALL_DISC_PER { get; set; }
        public Nullable<decimal> ORDER_VALUE { get; set; }
        public Nullable<decimal> STANDARD_DISCOUNT { get; set; }
        public Nullable<decimal> TOTAL_VAT { get; set; }
        public Nullable<decimal> TOTAL_ORDER_VALUE { get; set; }
        public Nullable<decimal> COST { get; set; }
        public Nullable<decimal> MARGIN { get; set; }
        public Nullable<decimal> MARGIN_PERCENT { get; set; }
        public Nullable<decimal> NET_VALUE { get; set; }
    }
}
