//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPPLIER_SUBCONTRACTOR
    {
        public int SUBCONTRACTOR_ID { get; set; }
        public Nullable<int> COMPANY_ID { get; set; }
        public string SUPPLIER_CODE { get; set; }
        public string BUSINESS_TYPE { get; set; }
        public string PARTNERSHIP_NAME { get; set; }
        public string PARTNERSHIP_UTR { get; set; }
        public string TRADING_NAME { get; set; }
        public string LEGAL_NAME { get; set; }
        public Nullable<bool> USE_LEGAL_NAME { get; set; }
        public string PRODUCE_STATEMENT { get; set; }
        public string CIS_TYPE { get; set; }
        public string CIS_CETT { get; set; }
        public string CIS_CERT_NO { get; set; }
        public Nullable<System.DateTime> DATE_LAST_VERIFIED { get; set; }
        public Nullable<System.DateTime> DATE_VALID_FROM { get; set; }
        public Nullable<System.DateTime> DATE_VALID_TO { get; set; }
        public string FORENAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string SURNAME { get; set; }
        public string UTR { get; set; }
        public string INSURANCE_NO { get; set; }
        public string CO_REG_NO { get; set; }
        public string STATUS_VERIFICATION { get; set; }
        public string VERIFICATION_NO { get; set; }
        public string TAX_TREATMENT { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public string STATUS { get; set; }
    }
}
