//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPPLIER
    {
        public int SUPPLIER_ID { get; set; }
        public Nullable<int> COMPANY_ID { get; set; }
        public string SUPPLIER_CODE { get; set; }
        public string SUPPLIER_NAME { get; set; }
        public Nullable<bool> IS_CUSTOMER { get; set; }
        public string ADDRESS { get; set; }
        public string POSTCODE { get; set; }
        public string COUNTRY { get; set; }
        public string WEBSITE { get; set; }
        public string STATEMENT { get; set; }
        public string SEND_MAIL { get; set; }
        public string DUNS_NO { get; set; }
        public string VAT_TYPE { get; set; }
        public string VAT_NUMBER { get; set; }
        public string DYNAMIC_DISC { get; set; }
        public string SUPPLIER_INACTIVE { get; set; }
        public string REGISTERED { get; set; }
        public string CREDIT_LIMIT { get; set; }
        public string CONTACT_TYPE { get; set; }
        public string CONTACT_NAME { get; set; }
        public string CONTACT_SALUTATION { get; set; }
        public string CONTACT_PHONE_NO { get; set; }
        public string CONTACT_EXTN_NO { get; set; }
        public string CONTACT_MOBILE_NO { get; set; }
        public string CONTACT_FAX { get; set; }
        public string EMAIL { get; set; }
        public string SKYPE { get; set; }
        public string PRICE_TYPE { get; set; }
        public Nullable<System.DateTime> DATE_STARTED { get; set; }
        public string CASH_ACC { get; set; }
        public Nullable<int> DEF_PMT_DAY { get; set; }
        public string GROUP { get; set; }
        public string GROUP_DESC { get; set; }
        public string SUB_CONTRACTOR { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public string STATUS { get; set; }
    }
}
