//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePOSDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAT_TYPE_LOOKUP
    {
        public string VAT_TYPE_NAME { get; set; }
        public int VAT_TYPE_ID { get; set; }
        public Nullable<bool> DELIVERY_TYPE_APPLICABLE { get; set; }
        public Nullable<bool> DELIVERY_MODE { get; set; }
    }
}
